import type { CatalogModel } from '@fbrx/shared';

const HF = 'https://huggingface.co';

/**
 * Curated GGUF models known to work with the built-in llama.cpp runtime and its tool calling (`--jinja`).
 * Checksums are recorded on first download; administrators can pin them via managed settings.
 */
export const MODEL_CATALOG: CatalogModel[] = [
  {
    id: 'qwen3-8b-q4km',
    name: 'Qwen3 8B',
    family: 'Qwen3',
    parameters: '8B',
    quantization: 'Q4_K_M',
    sizeBytes: 5_030_000_000,
    contextLength: 32768,
    url: `${HF}/bartowski/Qwen_Qwen3-8B-GGUF/resolve/main/Qwen_Qwen3-8B-Q4_K_M.gguf`,
    sha256: null,
    license: 'Apache-2.0',
    description: 'Recommended default. Strong tool use and reasoning; runs well on 16 GB machines and Apple Silicon.',
    tier: 'medium',
    toolCalling: true,
  },
  {
    id: 'qwen2.5-7b-instruct-q4km',
    name: 'Qwen2.5 7B Instruct',
    family: 'Qwen2.5',
    parameters: '7B',
    quantization: 'Q4_K_M',
    sizeBytes: 4_680_000_000,
    contextLength: 32768,
    url: `${HF}/bartowski/Qwen2.5-7B-Instruct-GGUF/resolve/main/Qwen2.5-7B-Instruct-Q4_K_M.gguf`,
    sha256: null,
    license: 'Apache-2.0',
    description: 'Reliable general assistant with good function calling.',
    tier: 'medium',
    toolCalling: true,
  },
  {
    id: 'llama-3.2-3b-instruct-q4km',
    name: 'Llama 3.2 3B Instruct',
    family: 'Llama 3.2',
    parameters: '3B',
    quantization: 'Q4_K_M',
    sizeBytes: 2_020_000_000,
    contextLength: 131072,
    url: `${HF}/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf`,
    sha256: null,
    license: 'Llama 3.2 Community License',
    description: 'Compact and fast; good for laptops with 8 GB of memory.',
    tier: 'small',
    toolCalling: true,
  },
  {
    id: 'qwen2.5-1.5b-instruct-q4km',
    name: 'Qwen2.5 1.5B Instruct',
    family: 'Qwen2.5',
    parameters: '1.5B',
    quantization: 'Q4_K_M',
    sizeBytes: 986_000_000,
    contextLength: 32768,
    url: `${HF}/bartowski/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf`,
    sha256: null,
    license: 'Apache-2.0',
    description: 'Smallest option for constrained machines; limited tool use.',
    tier: 'small',
    toolCalling: true,
  },
  {
    id: 'qwen3-14b-q4km',
    name: 'Qwen3 14B',
    family: 'Qwen3',
    parameters: '14B',
    quantization: 'Q4_K_M',
    sizeBytes: 9_000_000_000,
    contextLength: 32768,
    url: `${HF}/bartowski/Qwen_Qwen3-14B-GGUF/resolve/main/Qwen_Qwen3-14B-Q4_K_M.gguf`,
    sha256: null,
    license: 'Apache-2.0',
    description: 'Higher quality for workstations with 32 GB+ memory or a discrete GPU.',
    tier: 'large',
    toolCalling: true,
  },
  {
    id: 'gpt-oss-20b-mxfp4',
    name: 'gpt-oss 20B',
    family: 'gpt-oss',
    parameters: '20B (MoE)',
    quantization: 'MXFP4',
    sizeBytes: 12_100_000_000,
    contextLength: 131072,
    url: `${HF}/ggml-org/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-mxfp4.gguf`,
    sha256: null,
    license: 'Apache-2.0',
    description: 'Open-weight reasoning model with native tool use; needs ~16 GB of free memory.',
    tier: 'large',
    toolCalling: true,
  },
];
