/* Generated from the FBRX Library articles. Steps may contain <kbd> and <code> only. */
import type { IconName } from '@fbrx/ui';

export interface Article {
  id: string;
  cat: string;
  t: string;
  s: string;
  steps: string[];
  open?: string;
  go?: string;
  ask?: string;
}

export const CATS: Array<{ id: string; name: string; icon: IconName }> = [
  {
    id: 'basics',
    name: 'Basics',
    icon: 'globe',
  },
  {
    id: 'files',
    name: 'Files & folders',
    icon: 'folder',
  },
  {
    id: 'internet',
    name: 'Internet & Wi-Fi',
    icon: 'wifi',
  },
  {
    id: 'security',
    name: 'Security & privacy',
    icon: 'shield',
  },
  {
    id: 'speed',
    name: 'Speed & storage',
    icon: 'zap',
  },
  {
    id: 'devices',
    name: 'Printers & devices',
    icon: 'printer',
  },
  {
    id: 'display',
    name: 'Display & sound',
    icon: 'palette',
  },
  {
    id: 'accounts',
    name: 'Accounts & sign-in',
    icon: 'lock',
  },
  {
    id: 'backup',
    name: 'Backup & recovery',
    icon: 'download',
  },
  {
    id: 'shortcuts',
    name: 'Shortcuts',
    icon: 'terminal',
  },
  {
    id: 'trouble',
    name: 'Troubleshooting',
    icon: 'bug',
  },
  {
    id: 'fbrx',
    name: 'Using FBRX',
    icon: 'sparkles',
  },
];

export const ARTICLES: Article[] = [
  {
    id: 'screenshot',
    cat: 'basics',
    t: 'Take a screenshot',
    s: 'Capture your whole screen, a window or any area.',
    steps: [
      'Press <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> and drag over the area you want.',
      'The capture is copied — paste it anywhere with <kbd>Ctrl</kbd>+<kbd>V</kbd>.',
      'Click the notification to mark up or save it.',
      'Full screen to a file: <kbd>Win</kbd>+<kbd>PrtScn</kbd> (saved in Pictures → Screenshots).',
    ],
  },
  {
    id: 'record',
    cat: 'basics',
    t: 'Record your screen',
    s: 'Make a quick video of what you are doing.',
    steps: [
      'Open the Snipping Tool (search "Snipping Tool").',
      'Switch to the video camera icon and click New.',
      'Drag over the area and press Start. Click Stop when done, then Save.',
    ],
  },
  {
    id: 'install-app',
    cat: 'basics',
    t: 'Install and uninstall apps safely',
    s: 'Get apps from trusted places and remove ones you no longer use.',
    steps: [
      "Prefer the Microsoft Store or the developer's official website.",
      'Avoid "download" buttons on ads and sites offering cracked software.',
      'To remove an app: Settings → Apps → Installed apps → ⋯ → Uninstall.',
      'In FBRX: Updates → Apps can update everything installed through winget.',
    ],
    open: 'ms-settings:appsfeatures',
  },
  {
    id: 'default-apps',
    cat: 'basics',
    t: 'Change default apps',
    s: 'Choose which browser, PDF reader or music player opens files.',
    steps: ['Open Settings → Apps → Default apps.', 'Pick the app, then set it as default for the file types you want.'],
    open: 'ms-settings:defaultapps',
  },
  {
    id: 'clipboard',
    cat: 'basics',
    t: 'Use clipboard history',
    s: 'Paste something you copied earlier — not just the last thing.',
    steps: [
      'Press <kbd>Win</kbd>+<kbd>V</kbd> and turn on clipboard history the first time.',
      'From then on, <kbd>Win</kbd>+<kbd>V</kbd> shows everything you copied; click to paste.',
      'Pin items you paste often.',
    ],
    open: 'ms-settings:clipboard',
  },
  {
    id: 'emoji',
    cat: 'basics',
    t: 'Type emoji and symbols',
    s: 'Insert emoji, GIFs and special characters.',
    steps: ['Press <kbd>Win</kbd>+<kbd>.</kbd> (period).', 'Search, or switch tabs for symbols like ° © → and kaomoji.'],
  },
  {
    id: 'focus',
    cat: 'basics',
    t: 'Silence notifications (Do not disturb)',
    s: 'Stop pop-ups while you focus or present.',
    steps: [
      'Click the clock on the taskbar → the bell icon to turn on Do not disturb.',
      'Settings → System → Notifications lets you schedule it and choose priority apps.',
    ],
    open: 'ms-settings:notifications',
  },
  {
    id: 'startup',
    cat: 'basics',
    t: 'Stop apps opening at startup',
    s: 'Make your PC start faster by removing apps that launch automatically.',
    steps: [
      'Settings → Apps → Startup.',
      'Turn off anything you do not need right away (chat apps, updaters, launchers).',
      'Keep security software and drivers (audio, touchpad) on.',
    ],
    open: 'ms-settings:startupapps',
  },
  {
    id: 'find-file',
    cat: 'files',
    t: 'Find a lost file',
    s: 'Search by name, type or date.',
    steps: [
      'Press <kbd>Alt</kbd>+<kbd>Space</kbd> (FBRX Spotlight) and type part of the name.',
      'Or open File Explorer, click Home and use the search box (top-right).',
      'Search filters: <code>kind:pdf</code>, <code>datemodified:this week</code>, <code>size:>100MB</code>.',
    ],
    go: 'files',
  },
  {
    id: 'zip',
    cat: 'files',
    t: 'Zip and unzip files',
    s: 'Shrink files or send many as one.',
    steps: ['Select files, right-click → Compress to → ZIP file.', 'To extract: right-click the .zip → Extract All.'],
  },
  {
    id: 'extensions',
    cat: 'files',
    t: 'Show file extensions and hidden files',
    s: 'See whether a file is really .pdf or a disguised .exe.',
    steps: [
      'File Explorer → View → Show → File name extensions (and Hidden items).',
      'Be careful with files like <code>invoice.pdf.exe</code> — that is a program, not a document.',
    ],
  },
  {
    id: 'onedrive',
    cat: 'files',
    t: 'Understand OneDrive sync icons',
    s: 'What the cloud, check-mark and arrows mean.',
    steps: [
      'Cloud icon: online-only — downloads when opened.',
      'Green check outline: available on this PC.',
      'Solid green check: always kept on this device.',
      'Right-click → "Free up space" to make it online-only again.',
    ],
  },
  {
    id: 'recover-deleted',
    cat: 'files',
    t: 'Recover a deleted file',
    s: 'Get back something you deleted by mistake.',
    steps: [
      'Open the Recycle Bin on the desktop, right-click the file → Restore.',
      'For OneDrive files, check the OneDrive Recycle Bin on onedrive.com.',
      'Right-click the folder → Properties → Previous Versions (if File History was on).',
    ],
  },
  {
    id: 'share-nearby',
    cat: 'files',
    t: 'Send files to a nearby PC or phone',
    s: 'Nearby Sharing and Phone Link.',
    steps: [
      'Settings → System → Nearby sharing → My devices only (or Everyone nearby).',
      'Right-click a file → Share → pick the nearby PC.',
      'For your phone, open Phone Link and pair it.',
    ],
    open: 'ms-settings:crossdevice',
  },
  {
    id: 'wifi-fix',
    cat: 'internet',
    t: "Fix Wi-Fi that won't connect",
    s: 'The quick checklist that solves most Wi-Fi problems.',
    steps: [
      'Turn Wi-Fi off and on (taskbar network icon).',
      'Forget the network and reconnect with the password.',
      'Restart your router (unplug 30 s).',
      'Run FBRX Network Center → Overview → "Fix my internet".',
    ],
    go: 'network',
    ask: 'My Wi-Fi will not connect. Run network diagnostics and walk me through fixing it.',
  },
  {
    id: 'slow-internet',
    cat: 'internet',
    t: 'Why is my internet slow?',
    s: 'Find out if it is your PC, your Wi-Fi or your provider.',
    steps: [
      'Run a speed test in FBRX Network Center → Speed.',
      'Test again close to the router — if that is fast, the problem is Wi-Fi range.',
      'Pause big downloads, cloud sync and game updates.',
      'If wired is slow too, contact your internet provider with the results.',
    ],
    go: 'network',
  },
  {
    id: 'wifi-password',
    cat: 'internet',
    t: 'See the Wi-Fi password',
    s: 'Find the password of the network you are connected to.',
    steps: ['Settings → Network & internet → Wi-Fi → your network properties → "View Wi-Fi security key".', 'Or ask Fabrix: "show the Wi-Fi password".'],
    open: 'ms-settings:network-wifi',
  },
  {
    id: 'hotspot',
    cat: 'internet',
    t: 'Share your connection (mobile hotspot)',
    s: "Let your phone or another PC use this PC's internet.",
    steps: [
      'Settings → Network & internet → Mobile hotspot.',
      'Choose which connection to share and turn it on.',
      'Edit the name and password under Properties.',
    ],
    open: 'ms-settings:network-mobilehotspot',
  },
  {
    id: 'dns',
    cat: 'internet',
    t: 'Change DNS for faster, safer browsing',
    s: 'Use a privacy-friendly or filtering DNS like 1.1.1.1 or 9.9.9.9.',
    steps: [
      'Settings → Network & internet → your connection → Hardware properties → DNS server assignment → Edit.',
      'Choose Manual, IPv4 on, enter 1.1.1.1 and 1.0.0.1 (Cloudflare) or 9.9.9.9 (Quad9).',
      'Turn on DNS over HTTPS if offered.',
    ],
    open: 'ms-settings:network-status',
  },
  {
    id: 'vpn',
    cat: 'internet',
    t: 'Do I need a VPN?',
    s: 'What a VPN does — and does not do.',
    steps: [
      'A VPN hides your traffic from the local network (useful on public Wi-Fi) and changes your apparent location.',
      'It does not stop malware or phishing.',
      'Settings → Network & internet → VPN to add work VPNs.',
    ],
    open: 'ms-settings:network-vpn',
  },
  {
    id: 'phishing',
    cat: 'security',
    t: 'Spot a phishing e-mail',
    s: 'The signs of a fake message — and how to check a link safely.',
    steps: [
      'Urgency ("account suspended", "pay now") and unexpected attachments are red flags.',
      'Hover over links: does the real address match the company?',
      'Paste the link into FBRX Security → Link checker instead of clicking it.',
      'When in doubt, go to the website by typing it yourself.',
    ],
    go: 'security',
    ask: 'Teach me how to recognize phishing e-mails with a few realistic examples.',
  },
  {
    id: 'scan',
    cat: 'security',
    t: 'Scan for viruses',
    s: 'Run a Windows Defender scan.',
    steps: [
      'FBRX Security → Protection → Quick scan.',
      'Use Full scan if you think something is wrong; it takes longer.',
      'Right-click any file → Scan with Microsoft Defender.',
    ],
    go: 'security',
  },
  {
    id: 'passwords',
    cat: 'security',
    t: 'Use a password manager',
    s: 'Stop reusing passwords.',
    steps: [
      "Use your browser's built-in manager or a dedicated one (Bitwarden, 1Password).",
      'Generate a unique password for every site.',
      'Turn on two-factor authentication for e-mail and banking first.',
    ],
  },
  {
    id: 'passkeys',
    cat: 'security',
    t: 'Sign in with passkeys and Windows Hello',
    s: 'Face, fingerprint or PIN instead of passwords.',
    steps: ['Settings → Accounts → Sign-in options → set up Windows Hello.', 'Websites that support passkeys can then use Windows Hello to sign you in.'],
    open: 'ms-settings:signinoptions',
  },
  {
    id: 'privacy',
    cat: 'security',
    t: 'Check app permissions',
    s: 'See which apps can use your camera, microphone and location.',
    steps: ['Settings → Privacy & security → App permissions.', 'Turn off access for apps that do not need it.'],
    open: 'ms-settings:privacy',
  },
  {
    id: 'encryption',
    cat: 'security',
    t: 'Encrypt your drive',
    s: 'Protect your files if the laptop is lost.',
    steps: ['Settings → Privacy & security → Device encryption (or BitLocker on Pro).', 'Save the recovery key to your Microsoft account or print it.'],
    open: 'ms-settings:deviceencryption',
  },
  {
    id: 'scam-call',
    cat: 'security',
    t: '"Microsoft support" called me',
    s: 'Tech-support scams and what to do.',
    steps: [
      'Microsoft never calls you unexpectedly. Hang up.',
      'Never install remote-access apps (AnyDesk, TeamViewer) for a stranger.',
      'If you already did: disconnect from the internet, run a full scan, and change your passwords from another device.',
    ],
    ask: 'I think I fell for a tech support scam. What should I do right now, step by step?',
  },
  {
    id: 'free-space',
    cat: 'speed',
    t: 'Free up disk space',
    s: "Safely remove what you don't need.",
    steps: [
      'FBRX Storage → Clean up: temp files, Recycle Bin, Downloads.',
      'Turn on Storage Sense to keep it clean automatically.',
      'Uninstall big games and apps you no longer use.',
    ],
    go: 'storage',
  },
  {
    id: 'slow-pc',
    cat: 'speed',
    t: 'Speed up a slow PC',
    s: 'The changes that actually help.',
    steps: [
      'Restart — it clears memory and finishes updates.',
      'Disable unnecessary startup apps.',
      'Keep 15% of your drive free.',
      'Check FBRX Processes for apps using lots of CPU or memory.',
      'Plug in and choose Best performance in Settings → System → Power.',
    ],
    ask: 'My PC feels slow. Check CPU, memory, disk and startup apps and tell me what is slowing it down.',
  },
  {
    id: 'battery',
    cat: 'speed',
    t: 'Make the battery last longer',
    s: 'Power settings that matter.',
    steps: [
      'Settings → System → Power & battery → Energy saver.',
      'Lower screen brightness and refresh rate (gaming laptops: 60 Hz on battery).',
      'See what uses battery under Battery usage.',
      'FBRX Security → Bug catcher → "Battery health report" shows wear.',
    ],
    open: 'ms-settings:batterysaver',
  },
  {
    id: 'task-manager',
    cat: 'speed',
    t: 'Close a frozen app',
    s: 'When an app stops responding.',
    steps: [
      'Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd> to open Task Manager.',
      'Select the app → End task.',
      'Or use the FBRX Task Manager.',
    ],
  },
  {
    id: 'drive-health',
    cat: 'speed',
    t: 'Check if your drive is healthy',
    s: 'Spot a failing SSD or hard drive early.',
    steps: [
      'FBRX Storage → Drives shows health status.',
      'In Endpoint Ultra, Storage → Disks & partitions shows temperature, wear and error counters.',
      'Back up immediately if health is not "Healthy".',
    ],
    go: 'storage',
  },
  {
    id: 'printer-add',
    cat: 'devices',
    t: 'Add a printer',
    s: 'Connect a Wi-Fi or USB printer.',
    steps: [
      'Turn the printer on and connect it to the same Wi-Fi.',
      'Settings → Bluetooth & devices → Printers & scanners → Add device.',
      'If it is not found: "Add manually" and use its IP address (FBRX Network Center → Printers shows it).',
    ],
    open: 'ms-settings:printers',
    go: 'network',
  },
  {
    id: 'printer-stuck',
    cat: 'devices',
    t: 'Fix a stuck print queue',
    s: 'When nothing prints and jobs pile up.',
    steps: [
      'FBRX Security → Bug catcher → "Clear stuck print queue".',
      'Turn the printer off and on.',
      'Set the right printer as default (turn off "Let Windows manage my default printer").',
    ],
    go: 'security',
  },
  {
    id: 'bluetooth',
    cat: 'devices',
    t: 'Pair Bluetooth headphones',
    s: 'Connect earbuds, speakers, mice and controllers.',
    steps: [
      'Put the device in pairing mode (usually hold the power or pairing button).',
      'Settings → Bluetooth & devices → Add device → Bluetooth.',
      'Pick the device. If it fails, remove it and pair again.',
    ],
    open: 'ms-settings:bluetooth',
  },
  {
    id: 'monitor',
    cat: 'devices',
    t: 'Connect a second monitor or TV',
    s: 'Extend or duplicate your screen.',
    steps: [
      'Plug in HDMI / DisplayPort / USB-C.',
      'Press <kbd>Win</kbd>+<kbd>P</kbd> and choose Extend or Duplicate.',
      'Settings → System → Display to arrange screens and set resolution.',
    ],
    open: 'ms-settings:display',
  },
  {
    id: 'phone-link',
    cat: 'devices',
    t: 'Connect your phone (Phone Link)',
    s: 'Texts, calls, photos and notifications on your PC.',
    steps: ['Open Phone Link on the PC and follow the QR code.', 'Android: install "Link to Windows". iPhone: pair over Bluetooth.'],
    open: 'ms-settings:mobile-devices',
  },
  {
    id: 'webcam',
    cat: 'devices',
    t: 'Camera or microphone not working',
    s: 'Fix video calls.',
    steps: [
      'Check the privacy shutter or the camera key (F6 on many MSI laptops).',
      'Settings → Privacy & security → Camera / Microphone → allow access.',
      'Settings → System → Sound → Input → choose the right microphone.',
    ],
    open: 'ms-settings:privacy-webcam',
  },
  {
    id: 'night-light',
    cat: 'display',
    t: 'Easier on the eyes: night light & dark mode',
    s: 'Reduce blue light and glare.',
    steps: [
      'Settings → System → Display → Night light (schedule it at sunset).',
      'Settings → Personalization → Colors → Dark.',
      'In FBRX: Settings → Appearance for light/dark and themes.',
    ],
    open: 'ms-settings:nightlight',
  },
  {
    id: 'text-size',
    cat: 'display',
    t: 'Make text bigger',
    s: 'Read comfortably without squinting.',
    steps: ['Settings → Accessibility → Text size.', 'Or Settings → System → Display → Scale (125–150%).', 'In FBRX: Settings → Appearance → Text size.'],
    open: 'ms-settings:easeofaccess-display',
  },
  {
    id: 'sound-out',
    cat: 'display',
    t: 'No sound / wrong speakers',
    s: 'Pick the right output.',
    steps: [
      'Click the speaker icon on the taskbar → the arrow next to volume → choose the device.',
      'Settings → System → Sound → Volume mixer for per-app volume.',
    ],
    open: 'ms-settings:sound',
  },
  {
    id: 'wallpaper',
    cat: 'display',
    t: 'Personalize your desktop',
    s: 'Wallpaper, accent color and taskbar.',
    steps: ['Settings → Personalization → Background.', 'Colors → Accent color. Taskbar → alignment and items.'],
    open: 'ms-settings:personalization',
  },
  {
    id: 'pin',
    cat: 'accounts',
    t: 'Change your PIN or password',
    s: 'Update how you sign in.',
    steps: ['Settings → Accounts → Sign-in options → PIN (Windows Hello) → Change PIN.'],
    open: 'ms-settings:signinoptions',
  },
  {
    id: 'family',
    cat: 'accounts',
    t: 'Add a family member or guest account',
    s: 'Give others their own space.',
    steps: ['Settings → Accounts → Other users → Add account.', 'For kids, use Family Safety for screen-time and content filters.'],
    open: 'ms-settings:otherusers',
  },
  {
    id: 'lock',
    cat: 'accounts',
    t: 'Lock your PC when you step away',
    s: 'One shortcut keeps your stuff private.',
    steps: ['Press <kbd>Win</kbd>+<kbd>L</kbd>.', 'Settings → Accounts → Sign-in options → Dynamic lock locks it when your phone walks away.'],
  },
  {
    id: 'backup',
    cat: 'backup',
    t: 'Back up your files',
    s: 'Protect photos and documents.',
    steps: [
      'Windows Backup app: back up folders, settings and apps to OneDrive.',
      'Or copy important folders to an external drive regularly.',
      'Rule of thumb: 3 copies, 2 different places, 1 off-site.',
    ],
    ask: 'Help me design a simple, reliable backup plan for my PC.',
  },
  {
    id: 'restore-point',
    cat: 'backup',
    t: 'Create a restore point',
    s: 'An undo button for system changes.',
    steps: [
      'Search "Create a restore point" → System Protection → Configure → turn on for C:.',
      'Click Create before installing drivers or tweaking settings.',
      'To undo: same window → System Restore.',
    ],
  },
  {
    id: 'reset',
    cat: 'backup',
    t: 'Reset Windows (keep your files)',
    s: 'Last resort for a badly broken PC.',
    steps: ['Settings → System → Recovery → Reset this PC → Keep my files.', 'Apps are removed; your documents stay. Back up first anyway.'],
    open: 'ms-settings:recovery',
  },
  {
    id: 'usb-recovery',
    cat: 'backup',
    t: 'Make a recovery USB',
    s: 'Boot and repair a PC that will not start.',
    steps: [
      'Search "Recovery Drive" and follow the wizard (16 GB+ USB).',
      'Or create Windows 11 install media with the Media Creation Tool (Library → The Lab).',
    ],
  },
  {
    id: 'keys-essential',
    cat: 'shortcuts',
    t: 'Essential keyboard shortcuts',
    s: 'The 12 shortcuts worth memorizing.',
    steps: [
      '<kbd>Ctrl</kbd>+<kbd>C</kbd>/<kbd>V</kbd>/<kbd>X</kbd>/<kbd>Z</kbd> copy, paste, cut, undo',
      '<kbd>Alt</kbd>+<kbd>Tab</kbd> switch apps',
      '<kbd>Win</kbd>+<kbd>D</kbd> show desktop',
      '<kbd>Win</kbd>+<kbd>E</kbd> File Explorer',
      '<kbd>Win</kbd>+<kbd>←</kbd>/<kbd>→</kbd> snap windows',
      '<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> reopen closed browser tab',
      '<kbd>Alt</kbd>+<kbd>Space</kbd> FBRX Spotlight',
    ],
  },
  {
    id: 'snap',
    cat: 'shortcuts',
    t: 'Snap windows side by side',
    s: 'Multitask with snap layouts.',
    steps: [
      "Hover over a window's maximize button to pick a layout.",
      'Or press <kbd>Win</kbd>+<kbd>Z</kbd>.',
      'Snap groups remember sets of windows on the taskbar.',
    ],
  },
  {
    id: 'desktops',
    cat: 'shortcuts',
    t: 'Use virtual desktops',
    s: 'Separate work, school and play.',
    steps: ['<kbd>Win</kbd>+<kbd>Tab</kbd> → New desktop.', '<kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>←</kbd>/<kbd>→</kbd> to switch.'],
  },
  {
    id: 'restart',
    cat: 'trouble',
    t: 'Why "restart it" actually works',
    s: 'And the difference between shut down and restart.',
    steps: ['With Fast Startup, "Shut down" doesn\'t fully reset Windows — "Restart" does.', 'Restart at least once a week and after updates.'],
  },
  {
    id: 'bsod',
    cat: 'trouble',
    t: 'Blue screen (BSOD) happened',
    s: 'Find the cause of a crash.',
    steps: [
      'FBRX Security → Bug catcher lists recent stop errors.',
      'Update graphics, chipset and storage drivers.',
      'Run "Repair Windows image (DISM)" and "System File Checker".',
      'Run a memory test if it repeats (Library → The Lab → MemTest86+).',
    ],
    go: 'security',
    ask: 'My PC had a blue screen. Use get_bug_report to find out why and help me fix it.',
  },
  {
    id: 'update-stuck',
    cat: 'trouble',
    t: 'Windows Update is stuck or failing',
    s: 'Get updates installing again.',
    steps: ['Restart and try again.', 'FBRX Security → Bug catcher → "Reset Windows Update components".', 'Free up 20 GB of space for big feature updates.'],
    go: 'updates',
  },
  {
    id: 'no-boot',
    cat: 'trouble',
    t: "PC won't start",
    s: 'What to try before panicking.',
    steps: [
      'Hold the power button 15 s, unplug, then try again.',
      'Disconnect USB drives and docks.',
      'Interrupt boot 3 times to reach Recovery → Startup Repair.',
      'Use a recovery USB or Windows install USB → Repair your computer.',
    ],
  },
  {
    id: 'sfc',
    cat: 'trouble',
    t: 'Repair Windows system files',
    s: 'SFC and DISM explained.',
    steps: [
      'DISM repairs the Windows image; SFC then repairs system files from it.',
      'Run both from FBRX Security → Bug catcher (as administrator).',
      'Restart afterwards.',
    ],
    go: 'security',
  },
  {
    id: 'fbrx-fabric',
    cat: 'fbrx',
    t: 'Ask Fabrix anything',
    s: 'Your built-in assistant, offline by default.',
    steps: [
      'Open Fabrix from the sidebar or any "Ask Fabrix" button.',
      'Fabrix runs on your PC; it asks before going online for a chat.',
      'Approve or deny each action it wants to take.',
    ],
    go: 'agent',
  },
  {
    id: 'fbrx-spotlight',
    cat: 'fbrx',
    t: 'Spotlight: find anything with Ctrl+K',
    s: 'Apps, files, settings, commands and Fabrix — from anywhere.',
    steps: [
      'Press <kbd>Alt</kbd>+<kbd>Space</kbd> anywhere, or <kbd>Ctrl</kbd>+<kbd>K</kbd> inside FBRX.',
      'Type to search; press <kbd>Tab</kbd> to ask Fabrix.',
    ],
  },
  {
    id: 'fbrx-mesh',
    cat: 'fbrx',
    t: 'Connect your other computers',
    s: 'FBRX Mesh lets your PCs talk to each other.',
    steps: ['Mesh → Add a device → copy the join code.', 'Install FBRX on the other PC and enter the code.', 'Ask Fabrix: "check disk space on all my PCs".'],
    go: 'mesh',
  },
  {
    id: 'fbrx-advanced',
    cat: 'fbrx',
    t: 'Unlock advanced tools',
    s: 'Terminal, LAN scanner with SSH, Hyper-V Lab and more.',
    steps: ['Settings → Advanced → Unlock advanced tools.', 'Advanced tabs are marked with an "Advanced" pill.', 'Switch back to simple at any time.'],
    go: 'settings',
  },
];
